name: mobx_todos
description: "A new Flutter project."
version: 1.0.0+1


environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobx: ^2.6.0
  flutter_mobx: ^2.3.0
  provider: ^6.1.5+1
  json_annotation: ^4.10.0
  window_manager: ^0.3.8
  path_provider: ^2.1.4
  flutter_svg: ^2.0.10
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  mobx_codegen: ^2.7.6


flutter:
  uses-material-design: true
  assets:
    - assets/logos/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo-todos.png"


    